spring.application.name=valuation-tool
server.port=8082
spring.datasource.url=jdbc:postgresql://ep-fragrant-grass-ay9b25jj-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_aV2dI3tObMZA
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
logging.level.org.springframework.web=DEBUG
spring.jpa.defer-datasource-initialization=true
logging.level.org.springframework.security=DEBUG